workflows:
  ios-testflight:
    name: iOS TestFlight (soleco_website)
    max_build_duration: 60

    environment:
      flutter: stable
      vars:
        START_URL: https://soleco-optimizer-beta.azurewebsites.net/

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true

    scripts:
      - name: Flutter packages holen
        script: |
          flutter pub get

      - name: iOS bauen (IPA)
        script: |
          flutter build ipa --release \
            --dart-define=START_URL=$START_URL

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/logs/*.log

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_API_KEY
        key_id: $APP_STORE_CONNECT_KEY_ID
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
