workflows:
  ios-testflight:
    name: iOS TestFlight (soleco_website)
    max_build_duration: 60

    environment:
      flutter: stable
      vars:
        BUNDLE_ID: com.soleco.solecoWebsite
        START_URL: https://soleco-optimizer-beta.azurewebsites.net/

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true

    scripts:
      - name: Flutter packages holen
        script: |
          flutter pub get

      - name: Codemagic CLI Tools installieren
        script: |
          pip3 install -U codemagic-cli-tools

      - name: Keychain initialisieren
        script: |
          keychain initialize

      - name: Signing Files holen/erstellen (App Store / TestFlight)
        script: |
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create

      - name: Zertifikate in Keychain importieren
        script: |
          keychain add-certificates

      - name: Profiles im Xcode-Projekt setzen
        script: |
          xcode-project use-profiles

      - name: iOS bauen (IPA)
        script: |
          flutter build ipa --release \
            --dart-define=START_URL=$START_URL

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/logs/*.log

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_API_KEY
        key_id: $APP_STORE_CONNECT_KEY_ID
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
